#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

"""Convert a native Python virtual environment into an iOS build environment."""

from __future__ import annotations

import argparse
from importlib import util as importlib_util
import os
from pathlib import Path
import plistlib
import pprint
import shlex
from typing import Mapping, Sequence


def target_names(sdk: str, arch: str, deployment_target: str) -> tuple[str, str, str]:
    if sdk not in {"iphoneos", "iphonesimulator"}:
        raise ValueError(f"unsupported iOS SDK: {sdk}")
    multiarch = f"{arch}-{sdk}"
    platform_tag = f"ios-{deployment_target}-{arch}-{sdk}"
    target = f"{arch}-apple-ios{deployment_target}"
    if sdk == "iphonesimulator":
        target += "-simulator"
    return multiarch, platform_tag, target


def load_build_time_vars(sysconfigdata: Path) -> dict[str, object]:
    spec = importlib_util.spec_from_file_location(sysconfigdata.stem, sysconfigdata)
    if spec is None or spec.loader is None:
        raise ValueError(f"cannot load target sysconfig data: {sysconfigdata}")
    module = importlib_util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return dict(module.build_time_vars)


def localized_build_time_vars(
    original: Mapping[str, object], python_root: Path, wrappers: Mapping[str, Path]
) -> dict[str, object]:
    original_prefix = original.get("prefix")
    if not isinstance(original_prefix, str) or not original_prefix:
        raise ValueError("target sysconfig data does not define a usable prefix")

    localized: dict[str, object] = {}
    for key, value in original.items():
        if isinstance(value, str):
            value = value.replace(original_prefix, os.fspath(python_root))
            value = value.replace("-F .", f"-F {shlex.quote(os.fspath(python_root))}")
        localized[key] = value

    def target_link_command(key: str, wrapper: Path) -> str:
        value = localized.get(key)
        arguments = shlex.split(value) if isinstance(value, str) else []
        if arguments:
            arguments[0] = os.fspath(wrapper)
        else:
            arguments.append(os.fspath(wrapper))
        return shlex.join(arguments)

    localized.update(
        {
            "AR": os.fspath(wrappers["ar"]),
            "BLDSHARED": target_link_command("BLDSHARED", wrappers["clang"]),
            "CC": os.fspath(wrappers["clang"]),
            "CXX": os.fspath(wrappers["clang++"]),
            "LDCXXSHARED": target_link_command("LDCXXSHARED", wrappers["clang++"]),
            "LDSHARED": target_link_command("LDSHARED", wrappers["clang"]),
            "LINKCC": os.fspath(wrappers["clang"]),
            "RANLIB": os.fspath(wrappers["ranlib"]),
            "STRIP": os.fspath(wrappers["strip"]),
        }
    )
    return localized


def write_wrapper(path: Path, sdk: str, tool: str, target: str | None = None) -> None:
    arguments = ["/usr/bin/xcrun", "--sdk", sdk, tool]
    if target is not None:
        arguments.extend(("-target", target))
    command = " ".join(shlex.quote(argument) for argument in arguments)
    path.write_text(f"#!/bin/sh\nexec {command} \"$@\"\n", encoding="utf-8")
    path.chmod(0o755)


def write_cross_module(
    path: Path,
    *,
    sysconfig_name: str,
    multiarch: str,
    platform_tag: str,
    deployment_target: str,
    sdk: str,
    arch: str,
    python_root: Path,
) -> None:
    is_simulator = sdk == "iphonesimulator"
    source = f'''# Generated by configure_python_cross_venv.py.
import os
import platform
import subprocess
import sys
import sysconfig

os.environ["_PYTHON_HOST_PLATFORM"] = {platform_tag!r}
os.environ["_PYTHON_SYSCONFIGDATA_NAME"] = {sysconfig_name!r}
sys.cross_compiling = True
sys.platform = "ios"
sys.implementation._multiarch = {multiarch!r}
sys.base_prefix = {os.fspath(python_root)!r}
sys.base_exec_prefix = {os.fspath(python_root)!r}
subprocess._can_fork_exec = True

platform.system = lambda: "iOS"
platform.uname = lambda: platform.uname_result(
    "iOS", "build", {deployment_target!r}, "", {arch!r}
)
platform.ios_ver = lambda *args, **kwargs: platform.IOSVersionInfo(
    "iOS", {deployment_target!r}, {sdk!r}, {is_simulator!r}
)

sysconfig._get_sysconfigdata_name = lambda: {sysconfig_name!r}
sysconfig.get_platform = lambda: {platform_tag!r}
sysconfig._BASE_PREFIX = sys.base_prefix
sysconfig._BASE_EXEC_PREFIX = sys.base_exec_prefix
sysconfig._CONFIG_VARS = None
sysconfig._init_config_vars()
'''
    path.write_text(source, encoding="utf-8")


def configure_cross_venv(
    *,
    venv: Path,
    python_root: Path,
    sdk: str,
    arch: str,
    deployment_target: str,
    python_version: str,
) -> Path:
    venv = venv.resolve()
    python_root = python_root.resolve()
    venv_python = venv / "bin/python"
    if not venv_python.is_file():
        raise FileNotFoundError(f"native virtual environment is missing {venv_python}")

    framework_plist = python_root / "Python.framework/Info.plist"
    with framework_plist.open("rb") as handle:
        framework = plistlib.load(handle)
    expected_platform = "iPhoneSimulator" if sdk == "iphonesimulator" else "iPhoneOS"
    if framework.get("CFBundleSupportedPlatforms") != [expected_platform]:
        raise ValueError(f"Python framework does not target {expected_platform}")

    multiarch, platform_tag, target = target_names(sdk, arch, deployment_target)
    sysconfig_name = f"_sysconfigdata__ios_{multiarch}"
    sysconfig_source = python_root / f"lib/python{python_version}/{sysconfig_name}.py"
    if not sysconfig_source.is_file():
        raise FileNotFoundError(f"target sysconfig data is missing: {sysconfig_source}")

    site_packages = venv / f"lib/python{python_version}/site-packages"
    site_packages.mkdir(parents=True, exist_ok=True)
    wrappers = {
        name: venv / "bin" / f"{arch}-apple-{sdk}-{name}"
        for name in ("ar", "clang", "clang++", "ranlib", "strip")
    }
    for name, path in wrappers.items():
        write_wrapper(path, sdk, name, target if name in {"clang", "clang++"} else None)

    localized = localized_build_time_vars(
        load_build_time_vars(sysconfig_source), python_root, wrappers
    )
    with (site_packages / f"{sysconfig_name}.py").open("w", encoding="utf-8") as handle:
        handle.write(f"# Generated from {sysconfig_source}\n")
        handle.write("build_time_vars = ")
        pprint.pprint(localized, stream=handle, compact=True, sort_dicts=True)

    cross_module = site_packages / "_blender_ios_cross.py"
    write_cross_module(
        cross_module,
        sysconfig_name=sysconfig_name,
        multiarch=multiarch,
        platform_tag=platform_tag,
        deployment_target=deployment_target,
        sdk=sdk,
        arch=arch,
        python_root=python_root,
    )
    (site_packages / "_blender_ios_cross.pth").write_text(
        "import _blender_ios_cross\n", encoding="utf-8"
    )

    cross_file = venv / "ios-cross.ini"
    cross_file.write_text(
        "\n".join(
            (
                "[binaries]",
                f"ar = {os.fspath(wrappers['ar'])!r}",
                f"c = {os.fspath(wrappers['clang'])!r}",
                f"cpp = {os.fspath(wrappers['clang++'])!r}",
                f"cython = {os.fspath(venv / 'bin/cython')!r}",
                f"objc = {os.fspath(wrappers['clang'])!r}",
                f"objcpp = {os.fspath(wrappers['clang++'])!r}",
                f"python = {os.fspath(venv_python)!r}",
                f"ranlib = {os.fspath(wrappers['ranlib'])!r}",
                f"strip = {os.fspath(wrappers['strip'])!r}",
                "",
                "[host_machine]",
                "system = 'ios'",
                f"subsystem = {('ios-simulator' if sdk == 'iphonesimulator' else 'ios')!r}",
                f"cpu = {arch!r}",
                f"cpu_family = {('aarch64' if arch == 'arm64' else arch)!r}",
                "endian = 'little'",
                "",
                "[properties]",
                "needs_exe_wrapper = true",
                "longdouble_format = 'IEEE_DOUBLE_LE'",
                "",
                "[built-in options]",
                f"c_link_args = ['-F{python_root}', '-framework', 'Python']",
                f"cpp_link_args = ['-F{python_root}', '-framework', 'Python']",
                "",
            )
        ),
        encoding="utf-8",
    )
    return cross_file


def parse_arguments(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--venv", required=True, type=Path)
    parser.add_argument("--python-root", required=True, type=Path)
    parser.add_argument("--sdk", choices=("iphoneos", "iphonesimulator"), required=True)
    parser.add_argument("--arch", default="arm64")
    parser.add_argument("--deployment-target", required=True)
    parser.add_argument("--python-version", default="3.13")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    arguments = parse_arguments(argv)
    cross_file = configure_cross_venv(
        venv=arguments.venv,
        python_root=arguments.python_root,
        sdk=arguments.sdk,
        arch=arguments.arch,
        deployment_target=arguments.deployment_target,
        python_version=arguments.python_version,
    )
    print(cross_file)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
