diff --git a/GNUmakefile b/GNUmakefile
index 0266a9f2fdd..74e5df866da 100644
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -176,6 +176,20 @@ endif
 # System Vars
 OS:=$(shell uname -s)
 OS_NCASE:=$(shell uname -s | tr '[A-Z]' '[a-z]')
+# Path to host machine build folder. Cross compiled builds will require native host tools during build process.
+OS_NCASE_CROSSCOMPILE:=$(OS_NCASE)
+# Apple: ios and ios-simulator
+# iOS and iOS-Simulator libs will build to /ios{_simulator}_arm64 instead of /darwin_arm64.
+ifneq "$(findstring ios-simulator, $(MAKECMDGOALS))" ""
+	OS_NCASE:=ios-simulator
+	DEPS_ARGS:=-DAPPLE_TARGET_DEVICE=ios-simulator
+else ifneq "$(findstring ios, $(MAKECMDGOALS))" ""
+	OS_NCASE:=ios
+	DEPS_ARGS:=-DAPPLE_TARGET_DEVICE=ios
+else
+	DEPS_ARGS:=-DAPPLE_TARGET_DEVICE=macos
+endif
+
 CPU:=$(shell uname -m)
 
 # Use our OS and CPU architecture naming conventions.
@@ -204,6 +218,10 @@ ifndef BUILD_DIR
 	BUILD_DIR:=$(shell dirname "$(BLENDER_DIR)")/build_$(OS_NCASE)
 endif
 
+ifndef CROSSCOMPILE_BUILD_DIR
+	CROSSCOMPILE_BUILD_DIR:=$(shell dirname "$(BLENDER_DIR)")/build_$(OS_NCASE_CROSSCOMPILE)
+endif
+
 # Dependencies DIR's
 DEPS_SOURCE_DIR:=$(BLENDER_DIR)/build_files/build_environment
 
@@ -215,6 +233,26 @@ ifndef DEPS_INSTALL_DIR
 	DEPS_INSTALL_DIR:=$(BLENDER_DIR)/lib/$(OS_LIBDIR)_$(CPU)
 endif
 
+ifndef CROSSCOMPILE_DEPS_INSTALL_DIR
+	#CROSSCOMPILE_DEPS_INSTALL_DIR:=$(shell dirname "$(BLENDER_DIR)")/lib/$(OS_NCASE_CROSSCOMPILE)
+	#CROSSCOMPILE_DEPS_INSTALL_DIR:=$(BLENDER_DIR)/lib/$(OS_NCASE_CROSSCOMPILE)
+	# IOS_FIXME: "macos" should probably not be hardcoded?
+	CROSSCOMPILE_DEPS_INSTALL_DIR:=$(BLENDER_DIR)/lib/macos
+
+	# Add processor type to directory name, except for darwin x86_64
+	# which by convention does not have it.
+	ifeq ($(OS_NCASE_CROSSCOMPILE),darwin)
+		ifneq ($(CPU),x86_64)
+			CROSSCOMPILE_DEPS_INSTALL_DIR:=$(CROSSCOMPILE_DEPS_INSTALL_DIR)_$(CPU)
+		endif
+	else
+		CROSSCOMPILE_DEPS_INSTALL_DIR:=$(CROSSCOMPILE_DEPS_INSTALL_DIR)_$(CPU)
+	endif
+endif
+
+# For Cross-compiled builds, we pass in host dependencies path via crosscompile directory
+DEPS_CROSSCOMPILE_ARGS:=-DCMAKE_DEPS_CROSSCOMPILE_BUILDDIR=$(CROSSCOMPILE_BUILD_DIR) \
+					    -DCMAKE_DEPS_CROSSCOMPILE_INSTALLDIR=$(CROSSCOMPILE_DEPS_INSTALL_DIR)
 # Set the LIBDIR, an empty string when not found.
 LIBDIR:=$(wildcard $(BLENDER_DIR)/lib/${OS_LIBDIR}_${CPU})
 ifeq (, $(LIBDIR))
@@ -424,7 +462,19 @@ bpy: all
 developer: all
 ninja: all
 ccache: all
+tools: .FORCE
+	@echo
+	@echo Configuring Blender Host Tools in \"$(BUILD_DIR)\" ...
+	@$(CMAKE_CONFIG)
 
+	@echo
+	@echo Building Blender ...
+	$(BUILD_COMMAND) -C "$(BUILD_DIR)" -j $(NPROCS) glsl_preprocess
+	$(BUILD_COMMAND) -C "$(BUILD_DIR)" -j $(NPROCS) datatoc
+	$(BUILD_COMMAND) -C "$(BUILD_DIR)" -j $(NPROCS) makesrna
+	$(BUILD_COMMAND) -C "$(BUILD_DIR)" -j $(NPROCS) makesdna
+	$(BUILD_COMMAND) -C "$(BUILD_DIR)" -j $(NPROCS) msgfmt
+   	
 # -----------------------------------------------------------------------------
 # Build dependencies
 DEPS_TARGET = install
@@ -437,10 +487,12 @@ deps: export SOURCE_DATE_EPOCH = 1745584760
 deps: .FORCE
 	@echo
 	@echo Configuring dependencies in \"$(DEPS_BUILD_DIR)\", install to \"$(DEPS_INSTALL_DIR)\"
-
+	
 	@cmake -H"$(DEPS_SOURCE_DIR)" \
 	       -B"$(DEPS_BUILD_DIR)" \
-	       -DHARVEST_TARGET=$(DEPS_INSTALL_DIR)
+	       -DHARVEST_TARGET=$(DEPS_INSTALL_DIR) \
+	       ${DEPS_ARGS} \
+	       ${DEPS_CROSSCOMPILE_ARGS}
 
 	@echo
 	@echo Building dependencies ...
@@ -654,6 +706,12 @@ help_features: .FORCE
 
 clean: .FORCE
 	$(BUILD_COMMAND) -C "$(BUILD_DIR)" clean
+	
+# Do-nothing target so Make doesn't raise warning when we specify 'ios-{simulator}' in 'make deps ios{-simluator}'
+ios: .FORCE
+	@echo "iOS target detected"
+ios-simulator: .FORCE
+	@echo "iOS-simulator target detected"
 
 .PHONY: all
 
