if(NOT CMAKE_DEPS_CROSSCOMPILE_BUILDDIR)
  message(FATAL_ERROR "WITH_APPLE_CROSSPLATFORM requires CMAKE_DEPS_CROSSCOMPILE_BUILDDIR to point at the host dependency build tree")
endif()

if(NOT CMAKE_DEPS_CROSSCOMPILE_INSTALLDIR)
  set(
    CMAKE_DEPS_CROSSCOMPILE_INSTALLDIR
    "${CMAKE_CURRENT_BINARY_DIR}/../install/host"
    CACHE PATH "Host dependency install tree used by Apple cross-platform builds"
  )
endif()

set(CMAKE_DEPS_HOST_RELEASE_DIR "${CMAKE_DEPS_CROSSCOMPILE_BUILDDIR}/Release")
set(CMAKE_DEPS_HOST_PYTHON_DIR "${CMAKE_DEPS_HOST_RELEASE_DIR}/python")
set(CMAKE_DEPS_HOST_LLVM_DIR "${CMAKE_DEPS_HOST_RELEASE_DIR}/llvm")
set(CMAKE_DEPS_HOST_ISPC_DIR "${CMAKE_DEPS_HOST_RELEASE_DIR}/ispc")

message("\n------- Building libraries for Apple cross-platform target: ${APPLE_TARGET_DEVICE} -----\n")
message("CMAKE_DEPS_CROSSCOMPILE_BUILDDIR = ${CMAKE_DEPS_CROSSCOMPILE_BUILDDIR}")
message("CMAKE_DEPS_CROSSCOMPILE_INSTALLDIR = ${CMAKE_DEPS_CROSSCOMPILE_INSTALLDIR}")
message("CMAKE_DEPS_HOST_RELEASE_DIR = ${CMAKE_DEPS_HOST_RELEASE_DIR}")

set(MESON ${CMAKE_DEPS_HOST_PYTHON_DIR}/bin/meson)
